default_install_hook_types: [pre-commit, pre-push]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml

-   repo: local
    hooks:
    -   id: tests
        name: Run inference and logic tests
        entry: make test-full
        language: system
        stages: [pre-push]
        verbose: true
        require_serial: true
    
    -   id: format
        name: Format scripts with Black and isort
        entry: make format
        language: system
        stages: [pre-commit]
    
    -   id: lint
        name: Run linting with flake8, pydocstyle, naming and mypy
        entry: make lint
        language: system
        stages: [pre-commit]